#!/bin/bash
python3 manage.py loaddata categories.json
python3 manage.py loaddata products.json
echo "from authapp.models import User; User.objects.create_superuser('admin', 'admin@example.com', 'pass')" | python manage.py shell
